name: Run Tests

on: pull_request

jobs:
  run-tests:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Access MAPS_API_KEY
      env:
        MAPS_API_KEY: ${{ secrets.APOD_API_KEY }}
      run: echo MAPS_API_KEY=\"$MAPS_API_KEY\" > ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test

    - name: Run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
